version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - './.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html/src/public'
    ports:
      - '80:80'
    restart: always
    depends_on:
      - php
      - db

  php:
    build: ./.docker
    restart: always
    volumes:
      - '/home/daba/Рабочий стол/projects/online-shop/.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini:rw'
      - './.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './src/public:/var/www/html/src/public'
    env_file:
      - .env

  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'